site_name: icepack
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  favicon: 'images/logo.svg'
  logo: 'images/logo.svg'
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.indexes
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      toc_depth: 2
plugins:
  - mkdocs-jupyter
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/nord.css
nav:
  - Home: index.md
  - Install: install.md
  - Physics: physics.md
  - Tutorials:
    - tutorials/index.md
    - tutorials/00-meshes-functions.ipynb
    - tutorials/02-synthetic-ice-shelf.ipynb
  - Developers: developers.md
  - Contact: contact.md
